USE [master]
GO
/****** Object:  Database [P3_DB]    Script Date: 07-Jun-22 3:47:28 PM ******/
CREATE DATABASE [P3_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'P3_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\P3_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'P3_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\P3_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [P3_DB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [P3_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [P3_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [P3_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [P3_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [P3_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [P3_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [P3_DB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [P3_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [P3_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [P3_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [P3_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [P3_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [P3_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [P3_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [P3_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [P3_DB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [P3_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [P3_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [P3_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [P3_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [P3_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [P3_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [P3_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [P3_DB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [P3_DB] SET  MULTI_USER 
GO
ALTER DATABASE [P3_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [P3_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [P3_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [P3_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [P3_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [P3_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [P3_DB] SET QUERY_STORE = OFF
GO
USE [P3_DB]
GO
/****** Object:  User [ppp_user]    Script Date: 07-Jun-22 3:47:28 PM ******/
CREATE USER [ppp_user] FOR LOGIN [ppp_user] WITH DEFAULT_SCHEMA=[COMMON]
GO
/****** Object:  Schema [AUTH]    Script Date: 07-Jun-22 3:47:28 PM ******/
CREATE SCHEMA [AUTH]
GO
/****** Object:  Schema [COMMON]    Script Date: 07-Jun-22 3:47:28 PM ******/
CREATE SCHEMA [COMMON]
GO
/****** Object:  Schema [LT_COMMON]    Script Date: 07-Jun-22 3:47:28 PM ******/
CREATE SCHEMA [LT_COMMON]
GO
/****** Object:  Table [AUTH].[USERS]    Script Date: 07-Jun-22 3:47:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [AUTH].[USERS](
	[User_ID] [uniqueidentifier] NOT NULL,
	[Username] [varchar](30) NOT NULL,
	[email] [varchar](100) NOT NULL,
	[password] [text] NOT NULL,
 CONSTRAINT [PK_USERS_1] PRIMARY KEY CLUSTERED 
(
	[User_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [COMMON].[Case]    Script Date: 07-Jun-22 3:47:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [COMMON].[Case](
	[Case_ID] [uniqueidentifier] NOT NULL,
	[Manufacturer] [varchar](20) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Image] [image] NULL,
	[Price] [float] NOT NULL,
	[Form_Factor] [varchar](10) NOT NULL,
	[Fan_Size] [int] NOT NULL,
	[Fan_Count] [int] NOT NULL,
	[PSU_Inc] [bit] NOT NULL,
	[Wattage] [int] NULL,
	[TemperedGlassPanel_Inc] [bit] NOT NULL,
	[RGB_Inc] [bit] NOT NULL,
 CONSTRAINT [PK_Case] PRIMARY KEY CLUSTERED 
(
	[Case_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [COMMON].[CPU]    Script Date: 07-Jun-22 3:47:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [COMMON].[CPU](
	[CPU_ID] [uniqueidentifier] NOT NULL,
	[Socket] [varchar](10) NOT NULL,
	[CoreCount] [int] NOT NULL,
	[Frequency] [float] NOT NULL,
	[Manufacturer] [varchar](20) NOT NULL,
	[CacheSize] [float] NOT NULL,
	[CoolerInc] [bit] NOT NULL,
	[TDP] [int] NOT NULL,
	[Family] [varchar](25) NULL,
	[Architecture] [varchar](25) NULL,
	[ModelNo] [varchar](10) NULL,
	[Image] [image] NULL,
	[Name] [varchar](30) NOT NULL,
	[BoostFrequency] [float] NOT NULL,
	[Price] [float] NOT NULL,
 CONSTRAINT [PK_CPU] PRIMARY KEY CLUSTERED 
(
	[CPU_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [COMMON].[CPU_COOLER]    Script Date: 07-Jun-22 3:47:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [COMMON].[CPU_COOLER](
	[Cooler_ID] [uniqueidentifier] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Manufacturer] [varchar](20) NOT NULL,
	[Image] [image] NULL,
	[Price] [float] NOT NULL,
	[Fan_Size] [int] NOT NULL,
	[Type] [varchar](15) NOT NULL,
	[Max_TDP] [int] NOT NULL,
	[Fan_Count] [int] NOT NULL,
	[Noise] [int] NOT NULL,
 CONSTRAINT [PK_CPU_COOLER] PRIMARY KEY CLUSTERED 
(
	[Cooler_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [COMMON].[GPU]    Script Date: 07-Jun-22 3:47:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [COMMON].[GPU](
	[GPU_ID] [uniqueidentifier] NOT NULL,
	[Name] [varbinary](50) NOT NULL,
	[Price] [float] NOT NULL,
	[Image] [image] NULL,
	[Manufacturer] [varchar](20) NOT NULL,
	[Partner_Firm] [varchar](50) NOT NULL,
	[VRAM_Type] [varchar](10) NOT NULL,
	[VRAM_Volume] [int] NOT NULL,
	[Family] [varchar](15) NOT NULL,
	[Model] [varchar](15) NOT NULL,
	[Recommended_Power] [int] NOT NULL,
	[Core_Count] [int] NOT NULL,
	[Core_Freqeuncy] [int] NOT NULL,
	[Boost_Frequency] [int] NOT NULL,
	[Memory_Bandwith] [int] NOT NULL,
	[Memory_Frequency] [int] NOT NULL,
 CONSTRAINT [PK_GPU] PRIMARY KEY CLUSTERED 
(
	[GPU_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [COMMON].[M2]    Script Date: 07-Jun-22 3:47:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [COMMON].[M2](
	[M2_ID] [uniqueidentifier] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Manufacturer] [varchar](20) NOT NULL,
	[Image] [image] NULL,
	[Price] [float] NOT NULL,
	[Volume] [int] NOT NULL,
	[Read_Speed] [int] NOT NULL,
	[Write_Speed] [int] NOT NULL,
	[PCI_Version] [float] NOT NULL,
 CONSTRAINT [PK_M2] PRIMARY KEY CLUSTERED 
(
	[M2_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [COMMON].[Memory]    Script Date: 07-Jun-22 3:47:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [COMMON].[Memory](
	[Memory_ID] [uniqueidentifier] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Manufacturer] [varchar](20) NOT NULL,
	[Image] [image] NULL,
	[Price] [float] NOT NULL,
	[Memory_Type] [varchar](4) NOT NULL,
	[Memory_Frequency] [int] NOT NULL,
	[Memory_Volume] [int] NOT NULL,
	[Memory_Count] [int] NOT NULL,
	[Latency] [varchar](4) NOT NULL,
 CONSTRAINT [PK_Memory] PRIMARY KEY CLUSTERED 
(
	[Memory_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [COMMON].[Monitor]    Script Date: 07-Jun-22 3:47:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [COMMON].[Monitor](
	[Monitor_ID] [uniqueidentifier] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Manufacturer] [varchar](20) NOT NULL,
	[Image] [image] NULL,
	[Price] [float] NOT NULL,
	[Panel_Type] [varchar](5) NOT NULL,
	[Refresh_Rate] [int] NOT NULL,
	[Resolution] [varchar](10) NOT NULL,
	[Sync] [varchar](10) NULL,
	[Connection] [varchar](15) NOT NULL,
	[Brightness] [int] NOT NULL,
	[Has_HDR] [bit] NOT NULL,
	[HDR_Version] [varchar](10) NULL,
 CONSTRAINT [PK_Monitor] PRIMARY KEY CLUSTERED 
(
	[Monitor_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [COMMON].[MOTHERBOARD]    Script Date: 07-Jun-22 3:47:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [COMMON].[MOTHERBOARD](
	[MotherBoard_ID] [uniqueidentifier] NOT NULL,
	[Manufacturer] [varchar](20) NOT NULL,
	[MotherBoard_Socket] [varchar](10) NOT NULL,
	[Chipset] [varchar](10) NOT NULL,
	[MemorySlot_Count] [int] NOT NULL,
	[Memory_Frequency] [int] NOT NULL,
	[SoundCard] [varchar](30) NULL,
	[PCIe_Version] [float] NOT NULL,
	[PCIe_Max] [varchar](3) NOT NULL,
	[M2_Count] [int] NOT NULL,
	[SATA_Count] [int] NOT NULL,
	[USB_Version] [float] NOT NULL,
	[Image] [image] NULL,
	[Memory_Type] [varchar](4) NOT NULL,
	[Form_Factor] [varchar](10) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Price] [float] NOT NULL,
 CONSTRAINT [PK_MOTHERBOARD] PRIMARY KEY CLUSTERED 
(
	[MotherBoard_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [COMMON].[PSU]    Script Date: 07-Jun-22 3:47:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [COMMON].[PSU](
	[PSU_ID] [uniqueidentifier] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Manufacturer] [varchar](20) NOT NULL,
	[Image] [image] NULL,
	[Price] [float] NOT NULL,
	[Sertificate] [varchar](10) NULL,
	[Wattage] [int] NOT NULL,
	[Is_Modular] [bit] NOT NULL,
 CONSTRAINT [PK_PSU] PRIMARY KEY CLUSTERED 
(
	[PSU_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [COMMON].[SATA]    Script Date: 07-Jun-22 3:47:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [COMMON].[SATA](
	[SATA_ID] [uniqueidentifier] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Manufacturer] [varchar](20) NOT NULL,
	[Image] [image] NULL,
	[Price] [float] NOT NULL,
	[Volume] [int] NOT NULL,
	[Read_Speed] [int] NOT NULL,
	[Write_Speed] [int] NOT NULL,
	[RPM] [int] NULL,
 CONSTRAINT [PK_SATA] PRIMARY KEY CLUSTERED 
(
	[SATA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [LT_COMMON].[BUILD]    Script Date: 07-Jun-22 3:47:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [LT_COMMON].[BUILD](
	[Build_ID] [uniqueidentifier] NOT NULL,
	[CPU_ID] [uniqueidentifier] NOT NULL,
	[MotherBoard_ID] [uniqueidentifier] NOT NULL,
	[Memory_ID] [uniqueidentifier] NOT NULL,
	[GPU_ID] [uniqueidentifier] NULL,
	[Cooler__ID] [uniqueidentifier] NULL,
	[M2_ID] [uniqueidentifier] NULL,
	[SATA_ID] [uniqueidentifier] NULL,
	[Monitor_ID] [uniqueidentifier] NULL,
	[PSU_ID] [uniqueidentifier] NULL,
	[Case_ID] [uniqueidentifier] NULL,
	[User_ID] [uniqueidentifier] NOT NULL,
	[Price] [float] NOT NULL,
 CONSTRAINT [PK_BUILD] PRIMARY KEY CLUSTERED 
(
	[Build_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [LT_COMMON].[BUILD]  WITH CHECK ADD  CONSTRAINT [FK_BUILD_Case] FOREIGN KEY([Case_ID])
REFERENCES [COMMON].[Case] ([Case_ID])
GO
ALTER TABLE [LT_COMMON].[BUILD] CHECK CONSTRAINT [FK_BUILD_Case]
GO
ALTER TABLE [LT_COMMON].[BUILD]  WITH CHECK ADD  CONSTRAINT [FK_BUILD_CPU] FOREIGN KEY([CPU_ID])
REFERENCES [COMMON].[CPU] ([CPU_ID])
GO
ALTER TABLE [LT_COMMON].[BUILD] CHECK CONSTRAINT [FK_BUILD_CPU]
GO
ALTER TABLE [LT_COMMON].[BUILD]  WITH CHECK ADD  CONSTRAINT [FK_BUILD_CPU_COOLER] FOREIGN KEY([Cooler__ID])
REFERENCES [COMMON].[CPU_COOLER] ([Cooler_ID])
GO
ALTER TABLE [LT_COMMON].[BUILD] CHECK CONSTRAINT [FK_BUILD_CPU_COOLER]
GO
ALTER TABLE [LT_COMMON].[BUILD]  WITH CHECK ADD  CONSTRAINT [FK_BUILD_GPU] FOREIGN KEY([GPU_ID])
REFERENCES [COMMON].[GPU] ([GPU_ID])
GO
ALTER TABLE [LT_COMMON].[BUILD] CHECK CONSTRAINT [FK_BUILD_GPU]
GO
ALTER TABLE [LT_COMMON].[BUILD]  WITH CHECK ADD  CONSTRAINT [FK_BUILD_M2] FOREIGN KEY([M2_ID])
REFERENCES [COMMON].[M2] ([M2_ID])
GO
ALTER TABLE [LT_COMMON].[BUILD] CHECK CONSTRAINT [FK_BUILD_M2]
GO
ALTER TABLE [LT_COMMON].[BUILD]  WITH CHECK ADD  CONSTRAINT [FK_BUILD_Memory] FOREIGN KEY([Memory_ID])
REFERENCES [COMMON].[Memory] ([Memory_ID])
GO
ALTER TABLE [LT_COMMON].[BUILD] CHECK CONSTRAINT [FK_BUILD_Memory]
GO
ALTER TABLE [LT_COMMON].[BUILD]  WITH CHECK ADD  CONSTRAINT [FK_BUILD_Monitor] FOREIGN KEY([Monitor_ID])
REFERENCES [COMMON].[Monitor] ([Monitor_ID])
GO
ALTER TABLE [LT_COMMON].[BUILD] CHECK CONSTRAINT [FK_BUILD_Monitor]
GO
ALTER TABLE [LT_COMMON].[BUILD]  WITH CHECK ADD  CONSTRAINT [FK_BUILD_MOTHERBOARD] FOREIGN KEY([MotherBoard_ID])
REFERENCES [COMMON].[MOTHERBOARD] ([MotherBoard_ID])
GO
ALTER TABLE [LT_COMMON].[BUILD] CHECK CONSTRAINT [FK_BUILD_MOTHERBOARD]
GO
ALTER TABLE [LT_COMMON].[BUILD]  WITH CHECK ADD  CONSTRAINT [FK_BUILD_PSU] FOREIGN KEY([PSU_ID])
REFERENCES [COMMON].[PSU] ([PSU_ID])
GO
ALTER TABLE [LT_COMMON].[BUILD] CHECK CONSTRAINT [FK_BUILD_PSU]
GO
ALTER TABLE [LT_COMMON].[BUILD]  WITH CHECK ADD  CONSTRAINT [FK_BUILD_SATA] FOREIGN KEY([SATA_ID])
REFERENCES [COMMON].[SATA] ([SATA_ID])
GO
ALTER TABLE [LT_COMMON].[BUILD] CHECK CONSTRAINT [FK_BUILD_SATA]
GO
ALTER TABLE [LT_COMMON].[BUILD]  WITH CHECK ADD  CONSTRAINT [FK_BUILD_USERS] FOREIGN KEY([User_ID])
REFERENCES [AUTH].[USERS] ([User_ID])
GO
ALTER TABLE [LT_COMMON].[BUILD] CHECK CONSTRAINT [FK_BUILD_USERS]
GO
USE [master]
GO
ALTER DATABASE [P3_DB] SET  READ_WRITE 
GO
